#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers


db_name=$(ynh_app_setting_get $app db_name)
db_user==$db_name

#remove php-geoip
ynh_remove_app_dependencies
#removing emailpoubelle database
ynh_mysql_remove_db $db_user $db_name
#removing emailpoubelle directory
ynh_secure_remove /var/www/$app
#removing nginx conf
ynh_remove_nginx_config
#removing aliases
sed -i "/devnull:\/dev\/null/d" /etc/aliases
newaliases
# Remove hook for postfix conf
ynh_secure_remove "/usr/share/yunohost/hooks/conf_regen/98-postfix_emailpoubelle"

#remove cronjob
rm -f /etc/cron.d/emailpoubelle
yunohost service regen-conf postfix
service nginx reload
yunohost app ssowatconf
